stages:
  - package
  - linter
  - deploy

.deb-common:
  stage: package
  variables:
    DEBIAN_FRONTEND: noninteractive
  after_script:
    - mkdir --parents dist/
    - mv --verbose ../*.deb dist/
  script:
    - make deb
  artifacts:
    expire_in: 8 days
    paths:
      - dist/python3-aiostem_*.deb

python3-package:
  image: ${CI_REGISTRY}/dockers/ci/centos-build:8
  stage: package
  script:
    - python3 -m build --sdist --wheel
  artifacts:
    expire_in: 7 days
    paths:
      - dist/

debian10-package:
  image: ${CI_REGISTRY}/dockers/ci/debian-build:10
  extends: .deb-common

debian11-package:
  image: ${CI_REGISTRY}/dockers/ci/debian-build:11
  extends: .deb-common

python3-linter:
  image: ${CI_REGISTRY}/dockers/ci/centos-build:8
  stage: linter
  needs: []
  script:
    - make linter
  allow_failure: true

python3-deploy:
  image: ${CI_REGISTRY}/dockers/ci/centos-build:8
  stage: deploy
  variables:
    TWINE_REPOSITORY_URL: ${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
  needs:
    - python3-package
  script:
    - twine upload dist/aiostem-*.whl
  only:
    - tags
  when: manual
